apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfix
  template:
    metadata:
      labels:
        app: perfix
    spec:
      containers:
        - name: perfix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 150
            periodSeconds: 30
