apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfix
  template:
    metadata:
      labels:
        app: perfix
    spec:
      containers:
        - name: perfix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
