apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perfix-ing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: perfix-service
                port:
                  number: {{ .Values.service.port }}