apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfix
  template:
    metadata:
      labels:
        app: perfix
    spec:
      containers:
        - name: perfix
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 128Mi
              cpu: 500m
          env:
            - name: MODE
              value: "trial"
            - name: JDBC_POSTGRES_URL
              value: "jdbc:postgresql://postgres-service:{{ .Values.postgres.port }}/mydb"
            - name: PAC4J_BASEURL
              value: "https://{{ .Values.nginx.hostname }}/api"
            - name: PAC4J_GOOGLECLIENT_CLIENTID
              value: {{ .Values.backend.oauth.google.clientId }}
            - name: PAC4J_GOOGLECLIENT_SECRET
              value: {{ .Values.backend.oauth.google.secret }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.backend.aws.key }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.backend.aws.secret }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.backend.aws.region }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 150
            periodSeconds: 30
