apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfix
  template:
    metadata:
      labels:
        app: perfix
    spec:
      containers:
        - name: perfix
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          env:
            - name: MODE
              value: "trial"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 150
            periodSeconds: 30
