apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfix-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfix-ui
  template:
    metadata:
      labels:
        app: perfix-ui
    spec:
      containers:
        - name: perfix-ui
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 1024Mi
              cpu: 200m
          env:
            - name: NODE_ENV
              value: "production"
            - name: REACT_APP_BASE_URL
              value: https://{{ .Values.nginx.hostname }}/api
