# Steps to install nginx on k8s cluster
# git clone https://github.com/GoogleCloudPlatform/gke-networking-recipes.git
# cd gke-networking-recipes/ingress/single-cluster/ingress-ngnix
# kubectl create clusterrolebinding cluster-admin-binding \
#  --clusterrole cluster-admin \
#  --user $(gcloud config get-value account)
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/cloud/deploy.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: perfix-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /api(/|$)(.*) /$2 break;
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.nginx.hostname }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: perfix-ui-service
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api(/|$)(.*)
            backend:
              service:
                name: perfix-service
                port:
                  number: {{ .Values.backend.service.port }}