apiVersion: batch/v1
kind: Job
metadata:
  name: perfix-job
spec:
  template:
    spec:
      containers:
        - name: perfix-job
          image: "{{ .Values.job.image }}"
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for perfix service to be ready..."
              until curl --output /dev/null --silent --head --fail http://perfix-service:9000/health; do
                printf '.'
                sleep 5
              done
              echo "Perfix service is ready."
              curl -X POST http://perfix-service:9000/test -H 'Content-Type: application/json' -d '{\"key1\":\"value1\", \"key2\":\"value2\"}'
      restartPolicy: Never