apiVersion: v1
kind: Service
metadata:
  name: perfix-service
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: perfix
---
apiVersion: v1
kind: Service
metadata:
  name: perfix-ui-service
spec:
  selector:
    app: perfix-ui
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
  type: "{{ .Values.frontend.service.type }}"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres