backend:
  image:
    repository: mridulverma/perfix
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 9000

  aws:
    key: "key"
    secret: "secret"
    region: "us-east-1"

  oauth:
    google:
      clientId: "clientId"
      secret: "secret"

frontend:
  image:
    repository: mridulverma/perfix-ui
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 3000

nginx:
  hostname: "trials.perfix.in"

postgres:
  port: 5432

job:
  image: curlimages/curl
