backend:
  image:
    repository: mridulverma/perfix
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 9000

frontend:
  image:
    repository: mridulverma/perfix-ui
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 3000

nginx:
  hostname: "https://trials.perfix.com"

postgres:
  port: 5432

job:
  image: curlimages/curl
