# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      SBT_OPTS: -Xms1024M -Xmx4G -Xss2M -XX:MaxMetaspaceSize=2G
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Running Tests
      run: |
        # Set the heap size for SBT by setting the JAVA_OPTS environment variable.
        export JAVA_OPTS="-Xmx2048m" # Adjust the heap size as needed
        
        # Run the SBT tests
        sbt test

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish Docker Image
      if: success()
      run: |        
        # Build and publish the Docker image
        sbt "docker:publishLocal"
        docker push mridulverma/perfix:latest

    - name: Package Helm Chart
      if: success()
      run: helm package ./charts/perfix --destination .deploy

    - name: Publish Helm Chart
      if: success()
      uses: helm/chart-releaser-action@v1.2.1
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        charts_dir: charts
        chart_version: latest
        charts_repo_url: https://mridulv.github.io/perfix-charts
        token: ${{ secrets.GITHUB_TOKEN }}
