# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      SBT_OPTS: -Xms1024M -Xmx4G -Xss2M -XX:MaxMetaspaceSize=2G
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Running Tests
      if: success()
      run: |
        # Set the heap size for SBT by setting the JAVA_OPTS environment variable.
        export JAVA_OPTS="-Xmx2048m" # Adjust the heap size as needed
        
        # Run the SBT tests
        sbt test

    - name: Log in to Docker Hub
      if: success() && github.ref == 'refs/heads/master'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish Docker Image
      if: success() && github.ref == 'refs/heads/master'
      run: |
        # Build and publish the Docker image
        sbt "docker:publishLocal"
        docker push mridulverma/perfix:latest

    - name: Package and Publishing Helm package
      if: success() && github.ref == 'refs/heads/master'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        
        mkdir .deploy
        helm package charts/perfix --destination .deploy
        git fetch origin gh-pages
        git checkout gh-pages
        git reset --hard origin/gh-pages
        mv .deploy/* .
        helm repo index . --url https://mridulv.github.io/perfix/
        git add perfix-*.tgz index.yaml
        git commit -m "Publish Helm chart for $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin gh-pages
